// dashboard/src/App.jsx
import React, { useState, useEffect } from 'react'
import { telemetryService } from './services/api'
import Sidebar from './components/Sidebar'
import Navbar from './components/Navbar'
import SafetyHeroCard from './components/SafetyHeroCard'
import SensorMetricGrid from './components/SensorMetricGrid'
import TelemetryCharts from './components/TelemetryCharts'
import NodeMap from './components/NodeMap'
import AlertCenter from './components/AlertCenter'
import CameraScreeningPanel from './components/CameraScreeningPanel'
import ModelInsights from './components/ModelInsights'
import DeviceHealth from './components/DeviceHealth'
import WhatsAppModal from './components/WhatsAppModal'
import ThresholdConfigModal from './components/ThresholdConfigModal'

function App() {
  const [activeTab, setActiveTab] = useState('overview')
  const [latestData, setLatestData] = useState(null)
  const [historyData, setHistoryData] = useState([])
  const [alerts, setAlerts] = useState([])
  const [lastSyncTime, setLastSyncTime] = useState(null)
  const [isWaModalOpen, setIsWaModalOpen] = useState(false)
  const [isSidebarOpen, setIsSidebarOpen] = useState(false)

  const fetchData = async () => {
    try {
      const latestResp = await telemetryService.getLatest()
      setLatestData(latestResp.data)
      setLastSyncTime(new Date().toISOString())

      const historyResp = await telemetryService.getHistory()
      setHistoryData(historyResp.data)

      const alertsResp = await telemetryService.getAlerts()
      setAlerts(alertsResp.data)
    } catch (error) {
      console.error("Error fetching telemetry:", error)
    }
  }

  useEffect(() => {
    fetchData()
    const interval = setInterval(fetchData, 3000)
    
    // Listen for custom event from Navbar
    const handleWaOpen = () => setIsWaModalOpen(true)
    window.addEventListener('open-whatsapp-modal', handleWaOpen)
    
    return () => {
      clearInterval(interval)
      window.removeEventListener('open-whatsapp-modal', handleWaOpen)
    }
  }, [])

  return (
    <div className="flex min-h-screen bg-background">
      {/* Mobile Overlay */}
      {isSidebarOpen && (
        <div 
          className="fixed inset-0 bg-black/50 z-40 md:hidden transition-opacity"
          onClick={() => setIsSidebarOpen(false)}
        />
      )}

      {/* Left Navigation */}
      <Sidebar activeTab={activeTab} setActiveTab={setActiveTab} isSidebarOpen={isSidebarOpen} setIsSidebarOpen={setIsSidebarOpen} />

      {/* Main Content Area */}
      <div className="flex-1 flex flex-col min-w-0">
        <Navbar lastSyncTime={lastSyncTime} setIsSidebarOpen={setIsSidebarOpen} />

        <main className="flex-1 p-6 overflow-y-auto">
          <div className="max-w-[1600px] mx-auto flex flex-col gap-6">
            
            {/* Top Grid: Hero & Map */}
            <div className="grid grid-cols-1 xl:grid-cols-12 gap-6 h-auto xl:h-[300px]">
              <div className="xl:col-span-7 h-full">
                <SafetyHeroCard latestData={latestData} />
              </div>
              <div className="xl:col-span-5 h-[300px] xl:h-full">
                <NodeMap latestData={latestData} />
              </div>
            </div>

            {/* Middle Section: Sensor Cards */}
            <div className="w-full">
              <h3 className="text-sm font-semibold text-navy uppercase tracking-wider mb-4 pl-1">Live Telemetry</h3>
              <SensorMetricGrid latestData={latestData} historyData={historyData} />
            </div>

            {/* Analytics Grid */}
            <div className="grid grid-cols-1 xl:grid-cols-12 gap-6">
              <div className="xl:col-span-8">
                <TelemetryCharts historyData={historyData} />
              </div>
              <div className="xl:col-span-4 h-[400px]">
                <AlertCenter alerts={alerts} />
              </div>
            </div>

            {/* Intelligence & Hardware Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              <CameraScreeningPanel />
              <ModelInsights latestData={latestData} />
              <DeviceHealth />
            </div>
            
          </div>
        </main>
      </div>

      <WhatsAppModal isOpen={isWaModalOpen} onClose={() => setIsWaModalOpen(false)} />
      <ThresholdConfigModal />
    </div>
  )
}

export default App

// dashboard-angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SidebarComponent } from './components/sidebar/sidebar.component';
import { NavbarComponent } from './components/navbar/navbar.component';
import { TelemetryService, TelemetryData } from './services/telemetry.service';
import { ThresholdService } from './services/threshold.service';

import { SafetyHeroCardComponent } from './components/safety-hero-card/safety-hero-card.component';
import { SensorMetricGridComponent } from './components/sensor-metric-grid/sensor-metric-grid.component';
import { ThresholdConfigModalComponent } from './components/threshold-config-modal/threshold-config-modal.component';
import { NodeMapComponent } from './components/node-map/node-map.component';
import { TelemetryChartsComponent } from './components/telemetry-charts/telemetry-charts.component';
import { AlertCenterComponent } from './components/alert-center/alert-center.component';
import { CameraScreeningPanelComponent } from './components/camera-screening-panel/camera-screening-panel.component';
import { ModelInsightsComponent } from './components/model-insights/model-insights.component';
import { DeviceHealthComponent } from './components/device-health/device-health.component';
import { WhatsappModalComponent } from './components/whatsapp-modal/whatsapp-modal.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    CommonModule, SidebarComponent, NavbarComponent, SafetyHeroCardComponent, 
    SensorMetricGridComponent, ThresholdConfigModalComponent, NodeMapComponent, 
    TelemetryChartsComponent, AlertCenterComponent, CameraScreeningPanelComponent,
    ModelInsightsComponent, DeviceHealthComponent, WhatsappModalComponent
  ],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  activeTab: string = 'overview';
  isSidebarOpen: boolean = false;
  
  latestData: TelemetryData | null = null;
  historyData: TelemetryData[] = [];
  alerts: any[] = [];
  lastSyncTime: string | null = null;

  constructor(
    private telemetryService: TelemetryService,
    private thresholdService: ThresholdService
  ) {}

  ngOnInit() {
    this.fetchData();
    setInterval(() => this.fetchData(), 3000);
  }

  onSidebarToggle(isOpen: boolean) {
    this.isSidebarOpen = isOpen;
    setTimeout(() => window.dispatchEvent(new Event('resize')), 300);
  }

  async fetchData() {
    try {
      const latestResp = await this.telemetryService.getLatest();
      this.latestData = latestResp.data;
      this.lastSyncTime = new Date().toISOString();

      const historyResp = await this.telemetryService.getHistory();
      this.historyData = historyResp.data;

      const alertsResp = await this.telemetryService.getAlerts();
      this.alerts = alertsResp.data;
    } catch (error) {
      console.error("Error fetching telemetry:", error);
    }
  }
}

<div class="flex min-h-screen bg-background text-textMain">
  <!-- Mobile Overlay -->
  <div *ngIf="isSidebarOpen"
       class="fixed inset-0 bg-black/50 z-40 md:hidden transition-opacity"
       (click)="isSidebarOpen = false">
  </div>

  <!-- Left Navigation -->
  <app-sidebar 
    [(activeTab)]="activeTab" 
    [isSidebarOpen]="isSidebarOpen"
    (isSidebarOpenChange)="onSidebarToggle($event)">
  </app-sidebar>

  <!-- Main Content Area -->
  <div class="flex-1 flex flex-col min-w-0">
    <app-navbar 
      [lastSyncTime]="lastSyncTime" 
      (openSidebar)="onSidebarToggle(true)">
    </app-navbar>

    <main class="flex-1 p-6 overflow-y-auto">
      <div class="max-w-[1600px] mx-auto flex flex-col gap-6">
        
        <!-- Top Grid: Hero & Map -->
        <div *ngIf="activeTab === 'overview'" class="grid grid-cols-1 xl:grid-cols-12 gap-6 h-auto xl:h-[300px]">
          <div class="xl:col-span-7 h-full">
            <app-safety-hero-card [latestData]="latestData"></app-safety-hero-card>
          </div>
          <div class="xl:col-span-5 h-[300px] xl:h-full">
            <app-node-map [latestData]="latestData"></app-node-map>
          </div>
        </div>

        <!-- Middle Section: Sensor Cards -->
        <div *ngIf="activeTab === 'overview'" class="w-full">
          <h3 class="text-sm font-semibold text-navy uppercase tracking-wider mb-4 pl-1">Live Telemetry</h3>
          <app-sensor-metric-grid [latestData]="latestData"></app-sensor-metric-grid>
        </div>

        <!-- Analytics Grid -->
        <div *ngIf="activeTab === 'overview'" class="grid grid-cols-1 xl:grid-cols-12 gap-6">
          <div class="xl:col-span-8">
            <app-telemetry-charts [historyData]="historyData"></app-telemetry-charts>
          </div>
          <div class="xl:col-span-4 h-[400px]">
            <app-alert-center [alerts]="alerts"></app-alert-center>
          </div>
        </div>

        <!-- Intelligence & Hardware Grid -->
        <div *ngIf="activeTab === 'overview'" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <app-camera-screening-panel></app-camera-screening-panel>
          <app-model-insights [latestData]="latestData"></app-model-insights>
          <app-device-health></app-device-health>
        </div>
      </div>
    </main>
  </div>

  <app-whatsapp-modal></app-whatsapp-modal>
  <app-threshold-config-modal></app-threshold-config-modal>
</div>
