// dashboard-angular/src/app/components/sensor-metric-card/sensor-metric-card.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, Info, AlertCircle, CheckCircle2, AlertTriangle } from 'lucide-angular';
import { ThresholdService } from '../../services/threshold.service';
import { toSignal } from '@angular/core/rxjs-interop';

@Component({
  selector: 'app-sensor-metric-card',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  templateUrl: './sensor-metric-card.component.html',
  styleUrls: ['./sensor-metric-card.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SensorMetricCardComponent {
  @Input() config: any;
  @Input() value: number | null | undefined = null;

  thresholds = toSignal(this.thresholdService.thresholds$);

  readonly InfoIcon = Info;
  readonly AlertCircleIcon = AlertCircle;
  readonly CheckCircle2Icon = CheckCircle2;
  readonly AlertTriangleIcon = AlertTriangle;

  constructor(private thresholdService: ThresholdService) {}

  get health() {
    const t = this.thresholds();
    if (!t || !this.config || this.value === undefined || this.value === null) {
      return this.thresholdService.evaluateParameterHealth(this.config?.id, null, t);
    }
    return this.thresholdService.evaluateParameterHealth(this.config.id, this.value, t);
  }

  get progressPercent() {
    return Math.min(
      100,
      Math.max(8, ((this.value || 0) / (this.config?.maxScale || 100)) * 100)
    );
  }

  getIconForStatus(status: string) {
    if (status === 'safe') return this.CheckCircle2Icon;
    if (status === 'moderate') return this.AlertTriangleIcon;
    return this.AlertCircleIcon;
  }
}

<div *ngIf="config"
     class="relative rounded-xl border p-5 backdrop-blur-md transition-all duration-700 ease-in-out"
     [ngClass]="health?.cardClass">
     
  <div class="flex items-center justify-between">
    <div class="flex items-center space-x-2">
      <span class="text-sm font-semibold tracking-wide text-slate-200">
        {{ config.title }}
      </span>

      <div class="group relative flex items-center">
        <button
          type="button"
          class="text-slate-500 transition-colors duration-200 hover:text-cyan-400 focus:outline-none"
          [attr.aria-label]="'Hardware details for ' + config.title"
        >
          <lucide-icon [img]="InfoIcon" class="h-4 w-4 cursor-pointer"></lucide-icon>
        </button>

        <div class="pointer-events-none absolute -left-2 top-7 z-50 w-72 rounded-lg border border-slate-700/80 bg-slate-900/95 p-3.5 text-xs shadow-2xl backdrop-blur-md opacity-0 transition-all duration-200 ease-out group-hover:pointer-events-auto group-hover:opacity-100">
          <div class="border-b border-slate-800 pb-2">
            <p class="font-semibold text-cyan-400">{{ config.sensorName }}</p>
            <p class="text-[11px] text-slate-400">{{ config.sensorModel }}</p>
          </div>
          <div class="mt-2 space-y-1.5 text-slate-300">
            <p><span class="font-medium text-slate-400">Principle:</span> {{ config.principle }}</p>
            <p><span class="font-medium text-slate-400">Location:</span> {{ config.placement }}</p>
            <p><span class="font-medium text-slate-400">Calibration:</span> {{ config.calibration }}</p>
          </div>
        </div>
      </div>
    </div>

    <span
      class="flex items-center space-x-1.5 rounded-full border px-2.5 py-0.5 text-xs font-semibold tracking-wider transition-all duration-500 ease-in-out"
      [ngClass]="health?.badgeClass"
    >
      <lucide-icon *ngIf="health?.status" [img]="getIconForStatus(health.status)" class="h-3.5 w-3.5"></lucide-icon>
      <span>{{ health?.label }}</span>
    </span>
  </div>

  <div class="mt-4 flex items-baseline space-x-2">
    <span class="font-mono text-3xl font-bold tracking-tight text-white transition-colors duration-500">
      <ng-container *ngIf="value !== null && value !== undefined; else noValue">
        {{ value | number:'1.' + (config.precision || 1) + '-' + (config.precision || 1) }}
      </ng-container>
      <ng-template #noValue>--</ng-template>
    </span>
    <span class="text-sm font-medium text-slate-400">{{ config.unit }}</span>
  </div>

  <p class="mt-1 text-xs text-slate-400">
    Standard: <span class="text-slate-300 font-mono">{{ config.baselineText }}</span>
  </p>

  <div class="mt-4">
    <div class="h-1.5 w-full overflow-hidden rounded-full bg-slate-800/80">
      <div
        class="h-full rounded-full transition-all duration-700 ease-out"
        [ngClass]="health?.barColor + ' ' + health?.barGlow"
        [style.width.%]="progressPercent"
      ></div>
    </div>
  </div>
</div>

// dashboard/src/components/SensorMetricCard.jsx
import React from 'react';
import { Info, AlertCircle, CheckCircle2, AlertTriangle } from 'lucide-react';
import { evaluateParameterHealth } from '../utils/thresholdEvaluator';
import { useThresholds } from '../context/ThresholdContext';

export default function SensorMetricCard({ config, value }) {
  const { thresholds } = useThresholds();
  const health = evaluateParameterHealth(config.id, value, thresholds);

  const statusIcons = {
    safe: <CheckCircle2 className="h-3.5 w-3.5 text-emerald-400" />,
    moderate: <AlertTriangle className="h-3.5 w-3.5 text-amber-400" />,
    dangerous: <AlertCircle className="h-3.5 w-3.5 text-rose-400" />
  };

  const progressPercent = Math.min(
    100,
    Math.max(8, ((value ?? 0) / config.maxScale) * 100)
  );

  return (
    <div
      className={`relative rounded-xl border p-5 backdrop-blur-md transition-all duration-700 ease-in-out ${health.cardClass}`}
    >
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-2">
          <span className="text-sm font-semibold tracking-wide text-slate-200">
            {config.title}
          </span>

          <div className="group relative flex items-center">
            <button
              type="button"
              className="text-slate-500 transition-colors duration-200 hover:text-cyan-400 focus:outline-none"
              aria-label={`Hardware details for ${config.title}`}
            >
              <Info className="h-4 w-4 cursor-pointer" />
            </button>

            <div className="pointer-events-none absolute -left-2 top-7 z-50 w-72 rounded-lg border border-slate-700/80 bg-slate-900/95 p-3.5 text-xs shadow-2xl backdrop-blur-md opacity-0 transition-all duration-200 ease-out group-hover:pointer-events-auto group-hover:opacity-100">
              <div className="border-b border-slate-800 pb-2">
                <p className="font-semibold text-cyan-400">{config.sensorName}</p>
                <p className="text-[11px] text-slate-400">{config.sensorModel}</p>
              </div>
              <div className="mt-2 space-y-1.5 text-slate-300">
                <p><span className="font-medium text-slate-400">Principle:</span> {config.principle}</p>
                <p><span className="font-medium text-slate-400">Location:</span> {config.placement}</p>
                <p><span className="font-medium text-slate-400">Calibration:</span> {config.calibration}</p>
              </div>
            </div>
          </div>
        </div>

        <span
          className={`flex items-center space-x-1.5 rounded-full border px-2.5 py-0.5 text-xs font-semibold tracking-wider transition-all duration-500 ease-in-out ${health.badgeClass}`}
        >
          {statusIcons[health.status]}
          <span>{health.label}</span>
        </span>
      </div>

      <div className="mt-4 flex items-baseline space-x-2">
        <span className="font-mono text-3xl font-bold tracking-tight text-white transition-colors duration-500">
          {typeof value === 'number' ? value.toFixed(config.precision ?? 1) : '--'}
        </span>
        <span className="text-sm font-medium text-slate-400">{config.unit}</span>
      </div>

      <p className="mt-1 text-xs text-slate-400">
        Standard: <span className="text-slate-300 font-mono">{config.baselineText}</span>
      </p>

      <div className="mt-4">
        <div className="h-1.5 w-full overflow-hidden rounded-full bg-slate-800/80">
          <div
            className={`h-full rounded-full transition-all duration-700 ease-out ${health.barColor} ${health.barGlow}`}
            style={{ width: `${progressPercent}%` }}
          />
        </div>
      </div>
    </div>
  );
}
