// dashboard-angular/src/app/components/alert-center/alert-center.component.ts
import { Component, Input, OnChanges, SimpleChanges, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, AlertCircle, AlertTriangle, CheckCircle } from 'lucide-angular';

@Component({
  selector: 'app-alert-center',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  templateUrl: './alert-center.component.html',
  styleUrls: ['./alert-center.component.css']
})
export class AlertCenterComponent implements OnChanges {
  @Input() alerts: any[] = [];

  readonly AlertCircleIcon = AlertCircle;
  readonly AlertTriangleIcon = AlertTriangle;
  readonly CheckCircleIcon = CheckCircle;

  private alertAudio = new Audio('assets/sounds/hazard_alarm.mp3');
  private isAudioUnlocked = false;
  public isMuted = false;

  // Unlock audio on the first user interaction anywhere on the document
  @HostListener('document:click')
  unlockAudio(): void {
    if (!this.isAudioUnlocked) {
      this.alertAudio.load();
      this.isAudioUnlocked = true;
    }
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['alerts'] && this.alerts && this.alerts.length > 0) {
      const latestAlert = this.alerts[0];
      if (latestAlert.predicted_safety_level === 'Dangerous') {
        this.playCriticalAlert();
      }
    }
  }

  toggleMute(event: Event) {
    event.stopPropagation();
    this.isMuted = !this.isMuted;
  }

  playCriticalAlert(): void {
    if (this.isAudioUnlocked && !this.isMuted) {
      this.alertAudio.play().catch(err => console.warn('Audio blocked:', err));
    }
  }

  getAlertStyles(level: string) {
    if (level === 'Dangerous') return { icon: this.AlertCircleIcon, color: 'text-dangerous', bg: 'bg-dangerousBg' };
    if (level === 'Moderate') return { icon: this.AlertTriangleIcon, color: 'text-moderate', bg: 'bg-moderateBg' };
    return { icon: this.CheckCircleIcon, color: 'text-safe', bg: 'bg-safeBg' };
  }

  getTriggerText(alert: any): string {
    if (alert.ph < 6.5 || alert.ph > 8.5) return `pH bounds exceeded (${alert.ph.toFixed(1)})`;
    if (alert.turbidity_ntu > 10) return `High turbidity (${alert.turbidity_ntu.toFixed(0)} NTU)`;
    if (alert.ec_us_cm > 600) return `High EC (${alert.ec_us_cm.toFixed(0)} µS/cm)`;
    return "Multiple anomalies";
  }
}

<div class="card-panel flex flex-col h-full bg-white rounded-xl border border-border shadow-sm">
  <div class="p-4 border-b border-border flex justify-between items-center bg-surfaceHover">
    <div class="flex items-center gap-2">
      <h3 class="font-semibold text-navy">Alert Center</h3>
      <button (click)="toggleMute($event)" class="text-xs text-textMuted hover:text-navy px-1">
        {{ isMuted ? 'Unmute' : 'Mute' }}
      </button>
    </div>
    <span class="text-xs font-medium bg-moderateBg text-moderate px-2 py-1 rounded-full">
      {{ alerts?.length || 0 }} Recent Events
    </span>
  </div>

  <div class="flex-1 overflow-y-auto p-2">
    <div *ngIf="!alerts || alerts.length === 0" class="h-full flex items-center justify-center text-textMuted text-sm">
      No active alerts in this time period.
    </div>

    <div *ngIf="alerts && alerts.length > 0" class="flex flex-col gap-2">
      <div *ngFor="let alert of alerts | slice:0:8" class="flex gap-3 p-3 rounded-md hover:bg-surfaceHover transition-colors border border-transparent hover:border-border">
        
        <div class="mt-0.5 p-2 rounded-full shrink-0 h-max" [ngClass]="getAlertStyles(alert.predicted_safety_level).bg + ' ' + getAlertStyles(alert.predicted_safety_level).color">
          <lucide-icon [img]="getAlertStyles(alert.predicted_safety_level).icon" class="w-4 h-4"></lucide-icon>
        </div>
        
        <div class="flex-1 min-w-0">
          <div class="flex justify-between items-start mb-1">
            <div class="font-medium text-sm text-navy truncate">
              {{ getTriggerText(alert) }}
            </div>
            <div class="text-[10px] text-textMuted whitespace-nowrap ml-2">
              {{ alert.timestamp | date:'shortTime' }}
            </div>
          </div>
          <div class="flex justify-between items-center">
            <div class="text-xs text-textMuted truncate">Node: {{ alert.node_id }}</div>
            <button class="text-teal hover:text-navy text-[10px] font-semibold uppercase tracking-wider transition-colors">
              Acknowledge
            </button>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

// varuna-frontend/src/components/AlertCenter.jsx
import React from 'react';
import { AlertCircle, AlertTriangle, CheckCircle } from 'lucide-react';

export default function AlertCenter({ alerts }) {
  const getAlertStyles = (level) => {
    if (level === 'Dangerous') return { icon: AlertCircle, color: 'text-dangerous', bg: 'bg-dangerousBg' };
    if (level === 'Moderate') return { icon: AlertTriangle, color: 'text-moderate', bg: 'bg-moderateBg' };
    return { icon: CheckCircle, color: 'text-safe', bg: 'bg-safeBg' };
  };

  return (
    <div className="card-panel flex flex-col h-full">
      <div className="p-4 border-b border-border flex justify-between items-center bg-surfaceHover">
        <h3 className="font-semibold text-navy">Alert Center</h3>
        <span className="text-xs font-medium bg-moderateBg text-moderate px-2 py-1 rounded-full">
          {alerts?.length || 0} Recent Events
        </span>
      </div>

      <div className="flex-1 overflow-y-auto p-2">
        {!alerts || alerts.length === 0 ? (
          <div className="h-full flex items-center justify-center text-textMuted text-sm">
            No active alerts in this time period.
          </div>
        ) : (
          <div className="flex flex-col gap-2">
            {alerts.slice(0, 8).map((alert, idx) => {
              const style = getAlertStyles(alert.predicted_safety_level);
              const Icon = style.icon;
              
              // Determine primary trigger for display
              let triggerText = "Multiple anomalies";
              if (alert.ph < 6.5 || alert.ph > 8.5) triggerText = `pH bounds exceeded (${alert.ph.toFixed(1)})`;
              else if (alert.turbidity_ntu > 10) triggerText = `High turbidity (${alert.turbidity_ntu.toFixed(0)} NTU)`;
              else if (alert.ec_us_cm > 600) triggerText = `High EC (${alert.ec_us_cm.toFixed(0)} µS/cm)`;

              return (
                <div key={idx} className="flex gap-3 p-3 rounded-md hover:bg-surfaceHover transition-colors border border-transparent hover:border-border">
                  <div className={`mt-0.5 p-2 rounded-full ${style.bg} ${style.color} shrink-0 h-max`}>
                    <Icon className="w-4 h-4" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex justify-between items-start mb-1">
                      <div className="font-medium text-sm text-navy truncate">
                        {triggerText}
                      </div>
                      <div className="text-[10px] text-textMuted whitespace-nowrap ml-2">
                        {new Date(alert.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </div>
                    </div>
                    <div className="flex justify-between items-center">
                      <div className="text-xs text-textMuted truncate">Node: {alert.node_id}</div>
                      <button className="text-teal hover:text-navy text-[10px] font-semibold uppercase tracking-wider transition-colors">
                        Acknowledge
                      </button>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
