// dashboard-angular/src/app/components/device-health/device-health.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, Cpu, HardDrive, Wifi, Thermometer } from 'lucide-angular';

@Component({
  selector: 'app-device-health',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  templateUrl: './device-health.component.html',
  styleUrls: ['./device-health.component.css']
})
export class DeviceHealthComponent {
  readonly CpuIcon = Cpu;
  readonly HardDriveIcon = HardDrive;
  readonly WifiIcon = Wifi;
  readonly ThermometerIcon = Thermometer;
}

<div class="card-panel flex flex-col h-full bg-white rounded-xl border border-border shadow-sm">
  <div class="p-4 border-b border-border flex justify-between items-center bg-surfaceHover">
    <div class="flex items-center gap-2">
      <lucide-icon [img]="CpuIcon" class="w-4 h-4 text-teal"></lucide-icon>
      <h3 class="font-semibold text-navy">Edge Device Health</h3>
    </div>
    <span class="text-[10px] font-bold tracking-wider text-safe bg-safeBg px-2 py-0.5 rounded uppercase">Online</span>
  </div>

  <div class="p-4 flex-1 flex flex-col gap-4">
    <div class="grid grid-cols-2 gap-4">
      <!-- CPU -->
      <div>
        <div class="flex justify-between text-xs text-textMuted mb-1">
          <span>CPU Load</span>
          <span>42%</span>
        </div>
        <div class="h-1.5 w-full bg-surfaceHover rounded-full overflow-hidden">
          <div class="h-full bg-teal w-[42%] rounded-full"></div>
        </div>
      </div>
      <!-- RAM -->
      <div>
        <div class="flex justify-between text-xs text-textMuted mb-1">
          <span>Memory</span>
          <span>68%</span>
        </div>
        <div class="h-1.5 w-full bg-surfaceHover rounded-full overflow-hidden">
          <div class="h-full bg-teal w-[68%] rounded-full"></div>
        </div>
      </div>
    </div>

    <div class="grid grid-cols-2 gap-3 mt-2">
      <div class="flex items-center gap-3 p-2 rounded bg-surfaceHover border border-border">
        <lucide-icon [img]="ThermometerIcon" class="w-4 h-4 text-textMuted"></lucide-icon>
        <div>
          <div class="text-[10px] text-textMuted">Core Temp</div>
          <div class="text-xs font-semibold text-navy">45.2 °C</div>
        </div>
      </div>
      <div class="flex items-center gap-3 p-2 rounded bg-surfaceHover border border-border">
        <lucide-icon [img]="HardDriveIcon" class="w-4 h-4 text-textMuted"></lucide-icon>
        <div>
          <div class="text-[10px] text-textMuted">Storage</div>
          <div class="text-xs font-semibold text-navy">12.4 GB free</div>
        </div>
      </div>
    </div>

    <div class="mt-auto text-xs text-textMuted pt-2 border-t border-border flex justify-between">
      <span>Uptime: 14d 6h 22m</span>
      <span>v2.4.1-edge</span>
    </div>
  </div>
</div>

// varuna-frontend/src/components/DeviceHealth.jsx
import React from 'react';
import { Cpu, Server, Battery, Cloud, RefreshCw } from 'lucide-react';

export default function DeviceHealth() {
  const healthMetrics = [
    { label: "Raspberry Pi", value: "Online", icon: Cpu, status: "good" },
    { label: "ESP32 UART", value: "Connected", icon: Server, status: "good" },
    { label: "LTE Sync", value: "12ms ping", icon: Cloud, status: "good" },
    { label: "Battery", value: "98% (Solar)", icon: Battery, status: "good" },
    { label: "Last Sample", value: "2 mins ago", icon: RefreshCw, status: "good" },
  ];

  return (
    <div className="card-panel flex flex-col h-full">
      <div className="p-4 border-b border-border bg-surfaceHover">
        <h3 className="font-semibold text-navy">Device Health</h3>
      </div>
      
      <div className="p-4 flex flex-col gap-4 flex-1 justify-center">
        {healthMetrics.map((item, idx) => {
          const Icon = item.icon;
          return (
            <div key={idx} className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <Icon className="w-4 h-4 text-textMuted" />
                <span className="text-sm font-medium text-navy">{item.label}</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-sm text-textMuted">{item.value}</span>
                <span className="w-2 h-2 rounded-full bg-safe"></span>
              </div>
            </div>
          );
        })}
        
        <button className="mt-2 w-full py-2 border border-border text-teal text-sm font-medium rounded hover:bg-surfaceHover transition-colors">
          Run Remote Diagnostics
        </button>
      </div>
    </div>
  );
}
