// dashboard/src/components/CameraScreeningPanel.jsx
import React from 'react';
import { Camera, AlertCircle } from 'lucide-react';

export default function CameraScreeningPanel() {
  return (
    <div className="card-panel flex flex-col h-full">
      <div className="p-4 border-b border-border flex justify-between items-center bg-surfaceHover">
        <div className="flex items-center gap-2">
          <Camera className="w-4 h-4 text-teal" />
          <h3 className="font-semibold text-navy">AI-Assisted Particle Screening</h3>
        </div>
      </div>

      <div className="p-4 flex-1 flex flex-col gap-4">
        {/* Image Display */}
        <div className="w-full h-48 bg-navy rounded-lg overflow-hidden relative flex items-center justify-center">
          <div className="absolute top-2 left-2 bg-black/60 px-2 py-1 rounded text-[10px] text-white backdrop-blur">
            Latest Sample
          </div>
          {/* Synthetic representation of the bounding box image */}
          <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
            <rect width="100%" height="100%" fill="#1e293b" />
            {Array.from({ length: 15 }).map((_, i) => (
              <g key={i}>
                <circle cx={`${30 + Math.random() * 40}%`} cy={`${20 + Math.random() * 60}%`} r={Math.random() * 3 + 1} fill="#94a3b8" />
                <rect x={`calc(${30 + Math.random() * 40}% - 4px)`} y={`calc(${20 + Math.random() * 60}% - 4px)`} width="8" height="8" fill="none" stroke="#0ea5e9" strokeWidth="1" />
              </g>
            ))}
          </svg>
        </div>

        {/* Results Grid */}
        <div className="grid grid-cols-2 gap-3 text-sm">
          <div className="bg-surfaceHover p-3 rounded border border-border">
            <div className="text-textMuted text-xs mb-1">Detected Particles</div>
            <div className="font-bold text-navy">132</div>
          </div>
          <div className="bg-surfaceHover p-3 rounded border border-border">
            <div className="text-textMuted text-xs mb-1">Avg Size</div>
            <div className="font-bold text-navy">0.8 mm</div>
          </div>
        </div>

        {/* Disclaimer */}
        <div className="mt-auto flex items-start gap-2 bg-moderateBg/50 p-3 rounded border border-moderateBg text-xs text-moderate">
          <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
          <p>
            <strong>Screening support only.</strong> This optical classification does not serve as laboratory confirmation of microplastics or specific biological contaminants.
          </p>
        </div>
        
        <button className="w-full py-2 bg-surfaceHover hover:bg-slate-100 border border-border rounded text-sm font-medium text-navy transition-colors">
          Compare Recent Samples
        </button>
      </div>
    </div>
  );
}

// dashboard-angular/src/app/components/camera-screening-panel/camera-screening-panel.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, Camera, AlertCircle } from 'lucide-angular';

@Component({
  selector: 'app-camera-screening-panel',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  templateUrl: './camera-screening-panel.component.html',
  styleUrls: ['./camera-screening-panel.component.css']
})
export class CameraScreeningPanelComponent implements OnInit {
  readonly CameraIcon = Camera;
  readonly AlertCircleIcon = AlertCircle;

  lastUpdatedTimestamp = Date.now();
  syntheticPoints = Array.from({ length: 15 }).map(() => ({
    cx: `${30 + Math.random() * 40}%`,
    cy: `${20 + Math.random() * 60}%`,
    r: Math.random() * 3 + 1,
    x: `calc(${30 + Math.random() * 40}% - 4px)`,
    y: `calc(${20 + Math.random() * 60}% - 4px)`
  }));

  ngOnInit() {
    setInterval(() => {
      this.lastUpdatedTimestamp = Date.now();
    }, 5000);
  }

  // Cache-Busting Image URL logic as requested
  get latestCaptureUrl(): string {
    return `http://localhost:8000/api/v1/captures/latest_screen.jpg?t=${this.lastUpdatedTimestamp}`;
  }
}

<div class="card-panel flex flex-col h-full bg-white rounded-xl border border-border shadow-sm">
  <div class="p-4 border-b border-border flex justify-between items-center bg-surfaceHover">
    <div class="flex items-center gap-2">
      <lucide-icon [img]="CameraIcon" class="w-4 h-4 text-teal"></lucide-icon>
      <h3 class="font-semibold text-navy">AI-Assisted Particle Screening</h3>
    </div>
  </div>

  <div class="p-4 flex-1 flex flex-col gap-4">
    <!-- Image Display -->
    <div class="w-full h-48 bg-navy rounded-lg overflow-hidden relative flex items-center justify-center">
      <div class="absolute top-2 left-2 bg-black/60 px-2 py-1 rounded text-[10px] text-white backdrop-blur">
        Latest Sample
      </div>
      
      <!-- Cache-busting IMG -->
      <img [src]="latestCaptureUrl" class="w-full h-full object-cover" />

      <!-- Synthetic representation of the bounding box image -->
      <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="#1e293b" />
        <g *ngFor="let p of syntheticPoints">
          <circle [attr.cx]="p.cx" [attr.cy]="p.cy" [attr.r]="p.r" fill="#94a3b8" />
          <rect [attr.x]="p.x" [attr.y]="p.y" width="8" height="8" fill="none" stroke="#0ea5e9" stroke-width="1" />
        </g>
      </svg>
    </div>

    <!-- Results Grid -->
    <div class="grid grid-cols-2 gap-3 text-sm">
      <div class="bg-surfaceHover p-3 rounded border border-border">
        <div class="text-textMuted text-xs mb-1">Detected Particles</div>
        <div class="font-bold text-navy">132</div>
      </div>
      <div class="bg-surfaceHover p-3 rounded border border-border">
        <div class="text-textMuted text-xs mb-1">Avg Size</div>
        <div class="font-bold text-navy">0.8 mm</div>
      </div>
    </div>

    <!-- Disclaimer -->
    <div class="mt-auto flex items-start gap-2 bg-moderateBg/50 p-3 rounded border border-moderateBg text-xs text-moderate">
      <lucide-icon [img]="AlertCircleIcon" class="w-4 h-4 shrink-0 mt-0.5"></lucide-icon>
      <p>
        <strong>Screening support only.</strong> This optical classification does not serve as laboratory confirmation of microplastics or specific biological contaminants.
      </p>
    </div>
    
    <button class="w-full py-2 bg-surfaceHover hover:bg-slate-100 border border-border rounded text-sm font-medium text-navy transition-colors">
      Compare Recent Samples
    </button>
  </div>
</div>
